# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "v2"
type: "application"
name: "udm-listener"
description: "A Helm chart for the Univention Portal Provisioning API"
home: "https://www.univention.de/"

version: "0.1.0"

dependencies:
  - name: "nubus-common"
    version: "0.29.12"
    repository: "oci://artifacts.software-univention.de/nubus-dev/charts"
