# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH
---
replicaCount:
  dispatcher: 42
  udmTransformer: 42
  prefill: 42
  api: 42

nats:
  config:
    cluster:
      replicas: 42
  nats:
    image:
      registry: "registry.kyverno.test"
  natsBox:
    image:
      registry: "registry.kyverno.test"

api:
  image:
    tag: "0.42.0@sha256:c34020a9c402e204948df782e161329bc4644442d680397d2736024881b9d766"
